version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Checking code syntax..."
      - node -c app.js
artifacts:
  files:
    - app.js
    - package.json
    - node_modules/**/*